sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t angular-swagger2 .

script:
  - docker run -it angular-swagger2 bash -c
    "npm i && npm run install:demo &&
    npm run build &&
    npm test && npm run lint"
